---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: aks-flux-extension
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-flux-extension
  validation: client